ChromeGaming/Dot-Box

README.md
I have updated the README.md file to improve user-friendliness by including game rules and strategies for players. 
The game rules section provides detailed instructions for new players on how to play the game for the first time. It explains the objective of the game, how to mark sides to form squares, earn points, and continue playing until all boxes are occupied. Additionally, 
I have also added a strategies section to help players understand how to win the game. This section provides tips and tactics for strategic gameplay, such as focusing on completing squares, blocking opponents, and planning ahead to maximize points. 
These additions aim to enhance the overall user experience and make it easier for players to understand and enjoy the game.
Please review the following changes, which …
=> Updated Documentation under issue #87 GGSOC 24

index.html, js/game.js, style.css
Fixes # 125
Form Validation has been implemented succesfully.
The game shows warning to the user if he/she enter the values outside the contraints and prevents the starting the game.
<hr>
<hr>
--- 
<br>
=> form validation

index.html
issue #214
Added preloader.
Fixes #214
<hr>
<hr>
https://github.com/GameSphere-MultiPlayer/Dot-Box/assets/154777864/9e1cfc16-233e-475e-9ccc-76fe8a4ba55b
--- 
<br>
```
<style>
.preloader {
position: fixed;
top: 0;
left: 0;
width: 100%;
height: 100%;
background: black; 
display: flex;
justify-content: center;
align-items: center;
z-index: 9999; /* Ensure the preloader is above all other content */
}
.circle {
width: 200px; 
height: 200px;
background-color: black;
border-radius: 50%;
animation: circleAnimation 2s infinite linear, glowingBorder 2s infinite linear;
box-shadow: 0 0 20px 10px black; /* Adjusted shadow values */
}
.circle:before {
content: "";
position: absolute;
top: 5px;
left: 5px;
right: 5px;
bottom: 5px;
border-radius: 50%;
border: 3px solid transparent;
border-top-color: …
```
=> [New Feature]: Would u like to add preloader?

style.css
Fixes #1 
The issue was related to the responsiveness of the settings form. On smaller screens, the form elements were causing horizontal scrollbars, affecting the user experience negatively.
Changes Made:
- Implemented CSS adjustments to improve responsiveness and prevent horizontal overflow.
- Tested the updated styles on various screen sizes and browsers to validate compatibility and functionality.
<hr>
<hr>
--- 
<br>
=> Fixed responsiveness issue. #1

js/box.js, js/edge.js, package-lock.json, style.css
- User cliked Indicates color can be implemented if user clicked at last who is the user clicked indicates.
Fixes #231 
<hr>
<hr>
[Screencast from 2024-05-31 22-14-31.webm](https://github.com/ChromeGaming/Dot-Box/assets/121082414/99c3e9e1-264a-4e8a-a647-e64edf74d85f)
--- 
<br>
=> [Feature] : User cliked Indicates color

index.html
The PR resolves the Exit button bug - which was not working
Fixes #269
<hr>
- [ ✅] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [✅ ] I have performed a self-review of my own code or work.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [ ✅] My changes generates no new warnings.
- [✅ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [✅ ] I have added screenshot for review.
<hr>
--- 
<br>
=> Exit-button-bug-resolve  ~harshcodesit

.github/CONTRIBUTING_GUIDELINE.md
Updated contributing.md file
Fixes #106
=> Updated CONTRIBUTING_GUIDELINE.md

index.html, js/validation.js
Validation of the inserted values in Rows, Columns, and Players. Fixed #205 
Validate the value inserted by the user and show the message if not in range.
=> Added Validation of the inserted values in Rows, Columns, and Players.

index.html, js/game.js, style.css
Reverts ChromeGaming/Dot-Box#321
=> Revert "Added loader"

index.html, js/game.js, style.css
Fixes #41 
1.Done with the validations for all 3 input fields
2.added the reset button to reset input all values
3.remove increment/decrement operator for better ui
Fixes # <your_issue_number>
issue no - https://github.com/ChromeGaming/Dot-Box/issues/41
<hr>
- [x ] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [x ] I have commented my code, …
=> Done validation and added reset button on homepage

index.html, style.css
I have addressed and fixed the issue regarding the responsiveness of the home page. The page is now fully responsive for all screen sizes using best coding practices.
**Summary:**
- Implemented media queries to ensure responsiveness across different devices.
- Adjusted layout elements for an optimal viewing experience on smaller screens.
- Ensured that the detailed instructions/rules page can be included on the homepage or as a separate page, as per the project admin's instructions.
Issue:
Fixes #357
<hr>
<hr>
--- 
<br>
=> Made the UI completely responsive across all devices

index.html, style.css
Reverts ChromeGaming/Dot-Box#357
=> Revert "Made the UI completely responsive across all devices"

index.html, style.css
Reverts ChromeGaming/Dot-Box#359
=> Revert "Revert "Made the UI completely responsive across all devices""

index.html, instructions.html, style.css
Fixed UI made responsive and added new page - Instructions.html 
Fixes #356  
<hr>
<hr>
I am attacking demo video for reference - if you require I will attach screenshots as well
https://github.com/ChromeGaming/Dot-Box/assets/93462562/7e90b04c-c367-4ab9-b13d-973706da94a2
--- 
<br>
@Durgesh4993 and @ayush-t02 sir , I have closed previous PR and Now in this I have added new page instructions.html for those who are new to page and made it responsive for all the devices as mentioned in issue no. #356 . Please review this PR . Hopefully this  time there are no merge conflicts. Thank you
=> added instructions.html page for detailed instructions and made ui responsive for all devices

index.html, style.css
Added a user friendly Navbar in the homepage which include various options like logo , about us , home ,and contributors option to navigate easily, added basic hover effects to make it more attractive.
Fixes #198  
- [ x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] My changes generates no new warnings.
- [x ] I have added screenshot for review.
<hr>
before
after
--- 
<br>
please review and merge my PR for the issue #198 …
=> Added User Friendly Navbar issue #198

style.css
I've added a hover effect to the footer font style to provide better information and changed the color accordingly. The background color is compatible with "Chrome Gaming." I've also added a hover effect to improve its appearance when touched.
##Issue number:
#351 
<hr>
Before:
After:
On hover effect for 0.3sec will show black color:
--- 
<br>
=> Footer Style color

.vscode/settings.json, style.css
Made navbar responsive and its background transparent , made links better by adding transition , due to the complete game homepage the title "Maximise boxes" was overlapping to the other links of navbar , so to change that we need to completely change the homepage , so i made navlinks display to none for the smallest screen (that was the best solution I found), clearly visible upto the tablet screen , attaching images of all cases for your reference
Fixes issues #374 
<hr>
- [x ] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x] I have performed a self-review of my …
=> Made Navbar Responsive and changed background for better user experience issue #374

about.css, about.html
#380
ABOUT SECTION INFO ADDED  AND MODIFIED:
I have modify it and added infinte scrolling text type effect at last.Have attach screenshot also pllz check.I hope u liked it.Looking forward for ur response. If u need any changes do tell me.
<hr>
<br>
=> Enhancement: About section

instructions.html, style.css
The issues no . 389 has been fixed by modifying the Instruction section .
=> Fixed issue #389 : Instruction section

index.html, js/index.js, style.css
Added a proper fixed navbar at top
Fixes #399 
<hr>
<hr>
--- 
<br>
=> Added proper navbar at top

js/board.js, js/box.js, js/edge.js, js/game.js
I've added the  player's colour to the edges. 
Additionally, this led to me thinking, if we can add a following twist to the game: If all the four edges of the box are filled by a single player, the game is over. So not only do players have to fill the boxes but also to look out that some player doesn't fill all edges of the same box. 
I haven't implemented it, I'd like to know what the maintainers thought of it first. Thank you.
Fixes #395 
<hr>
-> Added colours to edges.
- [ x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x] I have performed a self-review of my …
=> Colour added to edges

index.html
i succesfully added reset button functionality
kindly merge my pr under gssoc24
=> added reset functionality

index.html, styles/index.style.css
Input Validation Error: Rows/Columns Allow Values beyond the range. I have fixed this issue by adding a warning note to enter between the range.
Fixes #392 
<hr>
<hr>
https://github.com/ChromeGaming/Dot-Box/assets/146202184/bfe286d5-60d2-43a1-b6b3-7c14082461cb
--- 
<br>
=> input validation

index.html, styles/index.style.css
Fixes # 388
<hr>
<hr>
--- 
<br>
=> Added footer in the home page

index.html
I we start game we start in a new page 
Fixes #425 
<hr>
<hr>
--- 
<br>
=> Made Game to start in new page

js/index.js
Fixed reset button  issue no #428
"By changing some code in index.js as by setting the reset button where the no. of rows and column set to the default one"
https://github.com/ChromeGaming/Dot-Box/assets/130289875/88747ac1-7faa-40e3-8b79-89d308a8862e
=> fixed reset button issue no #428

about.css, about.html
I have added Navbar in the 'About Us' page
Fixes: #420 
<hr>
<hr>
--- 
<br>
=> Added Navbar in About US Page

game.html
Sound Button Label Corrected in the Game from on to off.
Fixes #424 
<hr>
<hr>
--- 
<br>
=> Sound Button Label Corrected in Game

pages/FAQs.html, pages/about.html, pages/game.html, styles/about.css, styles/index.style.css
Added Back button in the games.html Page
Added Back button in FAQ.html page.
Added a consistent footer in the about.html
Fixes  #440 
<hr>
- [x ] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x] I have performed a self-review of my own code or work.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] My changes generates no new warnings.
- [ x] I have followed proper naming …
=> added back button to game.html and FAQ page

index.html
when we start games using lets go button the game is opened in the new page
Fixes #452 
<hr>
<hr>
--- 
<br>
=> Lets go page opens in the new page

js/FAQs.js, pages/FAQs.html
The drop down icons on FAQ page were not working
the icons were not changing and were inconsistent
The icons are now "+" by default and change to "-" when clicked.
Fixes #448 
<hr>
=> FAQ page dropdown behaviour fixed

index.html
Music button label corrected
Fixes #442 
<hr>
<hr>
--- 
<br>
=> Music button label corrected

pages/404.html, styles/index.style.css, styles/mainstyle.css
Fixes issue : #460 
Implemented a responsive grid system using CSS and added media queries to ensure elements resize and align correctly on smaller screens. Adjusted margins and padding for consistent spacing and verified the layout on various devices. These changes enhance the website's responsiveness and maintain a cohesive user experience across all screen sizes.
<hr>
<hr>
Mobile screen
Tab Screen
--- 
<br>
=> Fix Misaligned Elements on Small Screens

index.html
Hey @ayush-t02 and @Durgesh4993  issue closes #463 
I have fixed the Overlapping of the Feedback form on the Navbar and Footer
=> Fixed: The Feedback is Overlapping Navbar and Footer

index.html, pages/404.html, pages/FAQs.html, pages/about.html, pages/contributors.html, pages/game.html, pages/howtoplay.html, pages/privacypolicy.html, pages/termsofservice.html, styles/index.style.css, trail.js
Hey @ayush-t02 and @Durgesh4993
Fixes #462 
I have added the Cursor Trail Effect to the website across all the pages
https://github.com/ChromeGaming/Dot-Box/assets/163530398/a163fa6c-0ab6-432d-8afc-6ae26efab341
<hr>
<hr>
--- 
<br>
=> Added  Cursor Trail Effect To The Website 

index.html, styles/mainstyle.css
- Fixes #482
I have Added Reset Functionality and Thank You Pop Message After Submitting
https://github.com/ChromeGaming/Dot-Box/assets/101971980/3fbf145b-6714-4bcf-a716-9278eb8237fa
<hr>
- x ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
--- 
<br>
=> Added Reset Functionality and Thank You Pop Message After Submitting

pages/FAQs.html, styles/FAQs.css
Hey @ayush-t02,
issue closes #484 
I made the FAQ Page responsive for all screen sizes
Also, I have enhanced the "Back to home" Button 
Here is the output - 
https://github.com/ChromeGaming/Dot-Box/assets/131389695/abc2014f-d993-4dcc-85af-85d49823c76e
<hr>
<hr>
<br>
=> Made the FAQ Page "Responsive" and Enhanced "Back to Home" Button

styles/privacypolicy.css, styles/termsofservice.css
- Issue Fixes #483
I have made the pages of "Privacy Policy, and Terms of services" Responsive 
<hr>
<hr>
--- 
<br>
=> Made "Privacy Policy, and Terms of services" Pages Responsive 

index.html, pages/FAQs.html, pages/about.html, pages/contributors.html, pages/game.html, pages/howtoplay.html, pages/privacypolicy.html, pages/termsofservice.html
Hey @ayush-t02 ,
issue closes #486 
I have added the cursor trail effect in the absent pages.
Here is the output -
https://github.com/ChromeGaming/Dot-Box/assets/131389695/f5bd4de5-854b-4b46-9b05-9dbea188417c
<hr>
--- 
<br>
=> ✔️Added Cursor-Trail Effect in All the Pages.

index.html
hey @ayush-t02 
issue closes #485 
I have resolved the The "Music Off" Button not working, 
Now On Clicking the button it Turns off the music in the website.
Also, it reflects the text "Music Off" / "Music On" on clicking on it.
https://github.com/ChromeGaming/Dot-Box/assets/131389695/3afef4b9-b7eb-4acc-9918-24e5d37dceca
Please take a look and review it.
<hr>
--- 
<br>
=> ✔️ Resolved Music On/Off Button Issue!

index.html
I have made The Feedback Form "Responsive"
<hr>
<hr>
--- 
<br>
=> Made The Feedback Form "Responsive" #494

README.md
Added cd Dot-Box after clone the repository step and then correctly ordered the rest of the steps.
Fixes # 509
<hr>
<hr>
--- 
<br>
=> Added cd Dot-Box

index.html, pages/game.html, pages/licensing.html, styles/licensing.css
- Fixes #481
I have added the licensing page which reflects MIT License for Chrome gaming 
- Added dedicated page
- Made it responsive
- Match to website design theme
- Integrated back to home button
- integrated updated cursor trail effect
- Added Favicon
https://github.com/user-attachments/assets/70ab98e8-6116-4f78-b056-7c0357740370
<hr>
<hr>
--- 
<br>
=> Added Licensing Page Reflecting MIT License 

pages/game.html
- Issue Fixes #497 
I have Improved and Enhanced the overall Game interface and added some additional functionalities to  it:
- The **game works smooth** 
- **Enhanced Game User Interface**
- Added **Reset Functionality** so that if any user want to reset or restart the game they don't have navigate back to home 
- Added **SVG Icons, Animations and Hover effects** to the Buttosn to look more user friendly and meanigful
- Adde **Tooltip functionality** to the button, in case if any user is unable to understand what is the use of buttons
- Enhanced **Back to home Button** to look like home 
- Added **Updated Cursor trail Effect** to new one!
https://github.com/user-attachments/assets/514a1e42-5c51-4110-b40e-19fa647d8579
Added Tooltip for understanding the use of button …
=> "Enhanced the Game Interface" and Added "Reset Functionality" and "Aligned Buttons" with Icons

pages/about.html, styles/about.css
Changed that About's cards
Fixes #520
<hr>
<hr>
--- 
<br>
=> Modified the abot page's footer

index.html
Hey @ayush-t02   issue fixes #522 
The complete Ui of the home page was broken before, I have fixed and restored it 
- Fixed the **navbar.**
- Fixed and replaced the **broken CSS code.**
- Fixed and Added **Footer**.
- Restore the **Feedback** form.
- Integrated updated **cursor trail effect.**
- Fixed double **Tile Overflow.**
- Made the home page **Responsive**
https://github.com/user-attachments/assets/118c76b9-d8e7-4a27-9f7e-ed1c6a96316a
https://github.com/user-attachments/assets/d4a874e5-a8bb-437e-993f-7a94b304dd3f
Due to the breaking of Ui of the home page the page was not responsive, with the help of previous PR, I have made sure the page is responsive now!
<hr>
--- 
<be>
Please take a look and review it! thank you!
=> Fixed The "Broke UI" of Dot-Box "Home Page" including Tile Overflow

pages/FAQs.html, styles/FAQs.css
- Fixed the positioning of the Home button on FAQs page using CSS.
- Now the home button is not going to irritate while expanding the questions.
Fixes #526 
<hr>
<hr>
--- 
<br>
=> Fixed the positioning of the Home button on FAQs page

styles/mainstyle.css
- issue closes #537 
I have fixed The Feedback Thank You Pop Up is Alignment
<hr>
<hr>
--- 
<br>
=>  The Feedback Thank You Pop Up is Aligned

index.html, pages/404.html, pages/FAQs.html, pages/about.html, pages/contributors.html, pages/game.html, pages/howtoplay.html, pages/licensing.html, pages/privacypolicy.html, pages/termsofservice.html
- issue closes #540 
I have hide the trail effect in mobile view
https://github.com/user-attachments/assets/d94fb486-ca34-4744-a43d-fd5cb3bc65e3
<hr>
<hr>
--- 
<br>
=> feat: Hide the Trail Effect in Mobile View

styles/privacypolicy.css
Enhanced the privacy page
Fixes #528
<hr>
<hr>
--- 
<br>
=> Enhanced the privacy page

pages/game.html
- Issue fixes #525
I have added the interactive game tour guide to enhance the user experience by providing a step-by-step guide for the game's features. 
- The tour guide walks users through different components of the game interface, ensuring they understand the functionality of each element. 
- The guide includes buttons for navigating through the steps, skipping the tour, and closing the guide.
- Users can easily navigate through the tour steps using the navigation buttons.
- Added tour consists of multiple steps, each highlighting a specific component of the game.
- Added `Next Button`: Advances the tour to the next step.
- `Previous Button`: Returns to the previous step.
- `Skip Button`: Skips the entire tour and closes the guide.
- `Close Button`: Closes the tour …
=> Enhanced Game Intereface by Adding Tour Guide 

index.html
Fixed the Lets go button which was a link but it was placed inside a button which should not be the case
Fixes #498 
<hr>
<br>
=> Fixed the lets go button

pages/about.html, styles/about.css
- Issue fixes #548
I have Enhanced and Fixed the Ui of About us, also I have removed the unnecessary back to home button added by the chatbot contributor as the in navbar home navigation is already present!
Additionally, I have added Favicon to the page
https://github.com/user-attachments/assets/c432eab0-a1dd-49f1-b6c1-f4cb31fd35b0
Please take a look and review it!
<hr>
--- 
<br>
=> Enhanced and Fixed the Ui of About us 

pages/contributors.html
@ayush-t02 
- issue closes #575 
I have fixed the footer links in contributors page
https://github.com/user-attachments/assets/c305ab35-19f1-44eb-8faf-008f03dc5212
<hr>
<hr>
--- 
<br>
=> Fixed The Footer Links in Contributors Page

index.html
Added a draggable form with enhanced style
Fixes #555
<hr>
<hr>
https://www.awesomescreenshot.com/video/29818231?key=d258610ec6536182438713886324e208
--- 
<br>
=> Added a draggable form with enhanced style

pages/about.html
I have made the About us page responsive, additionally I have fixed the footer links as they were not working properly and gave error
https://github.com/user-attachments/assets/7173b37d-8bd5-4d7a-82cb-a7961fe30a15
<hr>
<hr>
--- 
<br>
=> Made About us page Responsive 

js/game.js, pages/game.html
Added live draggable scoreboard
Fixes #582 
<hr>
<hr>
--- 
<br>
=> Added live draggable scoreboard

pages/about.html, pages/contributors.html, pages/howtoplay.html, pages/licensing.html, pages/privacypolicy.html, pages/termsofservice.html
- issue closes #576 
I have added the vertical scrollbar across all the pages
<hr>
<hr>
<br>
=> Added Vertical ScrollBar Across All Pages 

pages/about.html, pages/contributors.html, pages/howtoplay.html, pages/licensing.html, pages/privacypolicy.html, pages/termsofservice.html
issue closes #574 
I have added scroll to top button in lengthy pages 
Contributors
How to play
About Us
Terms of Services
Licensing
Privacy Policy
<hr>
<hr>
--- 
<br>
=> Added Scroll to Top Button in Lengthy Pages

pages/game.html
- Issue fixes #599
I have added A New Tour Step guide Introducing Draggable Scoreboard 
<hr>
=> Added A New Tour Step guide Introducing Draggable Scoreboard

pages/contributors.html
issue closes #596 
I have Implemented the Diagonal-Transitional Effect to "Each Contributors Card" in the contributors page.
**Please take a look -** 
https://github.com/user-attachments/assets/2034403a-73ad-4c4c-8cdc-13bd67d3e33f
<hr>
--- 
<br>
=> ✔️Added Diagonal-Hovering Effect to Each Card!

pages/privacypolicy.html, pages/termsofservice.html, styles/termsofservice.css
issue closes #595 
I made the "Terms of Service" Page Styling Similar to the "Privacy Policy" Page to Improve the user engagement and consistency across the Website;
- Also Added Favicons to both :Terms of Service and Privacy policy page.
**Here as you can see-** 
https://github.com/user-attachments/assets/9b6f4658-0bc1-44d7-ad4f-2e8b1105a919
<hr>
<hr>
--- 
<br>
=> ✔️Styled "Terms Of Service" Page!

pages/FAQs.html, styles/FAQs.css
- Issue fixes #583 
I have:
-  **Enhanced the Ui** of the FAQ Page
- Adjust and added **proper alignments**
- Integrated **navbar** and **footer**
- Enhanced the working of **accordion** (if one answer is open then previous one closes)
- Added **vertical scrollbar** 
- Remove the back to **home** button
- Made it **Responsive**
<hr>
--- 
<br>
=> Enhance Ui of FAQs Page: Proper Alignments, FIx Accordian and Make it Responsive 

styles/licensing.css
Enhanced the licensing page
Fixes #580
<hr>
<hr>
--- 
<br>
=> Enhanced the Licensing page

pages/howtoplay.html, pages/licensing.html, pages/privacypolicy.html, pages/termsofservice.html
- issue closes #605 
I have added the favicon to the missing pages
<hr>
<hr>
--- 
<br>
=> Added the Favicon to The missing pages

pages/licensing.html, pages/privacypolicy.html, pages/termsofservice.html
- issue closes #604 
I have added the back to home button and make the pages responsive
<hr>
<hr>
--- 
<br>
=> Added the Back to Home Button and Make The Pages Responsive

pages/about.html, pages/contributors.html, pages/howtoplay.html, pages/licensing.html, pages/privacypolicy.html, pages/termsofservice.html
- issue closes #625 
I have Styled and Added Animation to the Scroll to Top Button Match to Website Design Theme 
https://github.com/user-attachments/assets/d6c7682f-78c5-4017-9695-01c9ca427e30
<hr>
<hr>
--- 
<br>
=> Styled and Added Animation to the Scroll to Top Button Match to Website Design Theme 

index.html, pages/404.html, pages/FAQs.html, pages/about.html, pages/contributors.html, pages/game.html, pages/howtoplay.html, pages/licensing.html, pages/privacypolicy.html, pages/termsofservice.html
- issue closes #627 
I have redesigned the trail effect to match the website theme
https://github.com/user-attachments/assets/7aef24ad-6a16-47d6-9bf8-4a713f52baa4
<hr>
<hr>
--- 
<br>
=> Redesigned the Trail Effect Match to the Website Theme

js/game.js, js/index.js, pages/game.html, styles/game.style.css, styles/mainstyle.css
Fixed bugs that were created with previous scoreboard PR merge. 
Issues resolved:
1. Fixed theme
2. Sound toggle button is fixed and in working condition
3. Aligned the page correctly and removed unnecessary scrolling
4. Clickable sound system is fixed
I have removed the new sound toggle button as it was already present in the game and does not need 2 sound toggle button. It was creating bugs and was giving errors.
the ready button was not defined and was initialised with event listener, I have commented that code and can be used in future .
Fixes #634 
<hr>
<hr>
Now this code won't give warnings or errors that were previously present.
--- 
<br>
=> Bugs Fixed

pages/FAQs.html, styles/FAQs.css
Hey @ayush-t02
issue closes #532 
I have improved the FAQ Section in the Website
- added hovering effects to the page
- added text shadows
- added transition effects to the questions 
https://github.com/user-attachments/assets/6f785333-6918-4f8c-8c73-ff5a46e5b087
<hr>
=> ✔️Improved FAQ Section Of the Website !

pages/contributors.html
Earlier the CSS was ugly between the screen width of 1166px and 769px, inclusive.
Fixes #633 
<hr>
<hr>
--- 
<br>
=> Corrected Contributors' Profile picture

pages/licensing.html
Corrected the License page.
Fixes #629
<hr>
<hr>
--- 
<br>
=> Corrected container width of license page

js/navbar.js, pages/FAQs.html, pages/about.html, pages/contributors.html, pages/howtoplay.html, styles/FAQs.css, styles/mainstyle.css, styles/navbar.css
I added and/or modified the nav-bar to be consistent in all the following pages:
- About Page
- Contributors Page
- How to Play Page
- FAQs Page
The theme of these pages is totally different, and there is no nav-bar at all in these pages:
- Privacy Policy Page
- Licensing Page
- Terms of Service Page
The **Home screen** layout is not responsive enough for mobile devices,, and I have avoided making any change in it fuee to the following two reasons:
- to avoid possible conflicts.
- the new navbar won't be useable  enough in the current conditions of the home-page
Fixes #624
<hr>
<hr>
**Screenshots**
--- 
<br>
=> Added hamburger Menu to all the required pages

pages/howtoplay.html, styles/howtoplay.css
Enhanced the How to play page
Fixes #608
<hr>
<hr>
--- 
<br>
=> Enhanced the How to Play page

pages/about.html, pages/licensing.html, pages/privacypolicy.html, pages/termsofservice.html
- issue closes #637
I have fixed the navigation and back to home buttons result in 404 page not found error
https://github.com/user-attachments/assets/216ac428-ad46-403c-b51e-cfdb0f335911
<hr>
--- 
<br>
=> Fix Navigations and Back to Home Buttons Result in 404 Page Not Found Error 

pages/game.html
Hey @ayush-t02  | Issues fixes #598 
- Adjusted the default position of the draggable scoreboard to prevent overlap with the game board.
- This ensures that users no longer need to manually reposition the scoreboard every time they start a game.
- Improved the smoothness of interactions with the scoreboard and other UI elements to enhance overall usability.
- Hidden the draggable scoreboard in mobile views to avoid occupying the entire screen, which previously led to the overlap of game interface elements and display buttons. Made the scoreboard responsive for other devices to prevent overlap with the game board.
-  This ensures a smooth and unobstructed user experience across different screen sizes.
- Fixed the timer’s position and alignment, making it more accessible and responsive. …
=>  Enhanced and Improved "Draggable Scoreboard Functionality" and Game interface

index.html, js/loader.js, js/maingame.js, js/validation.js, pages/404.html, pages/FAQs.html, pages/about.html, pages/contributors.html, pages/game.html, pages/howtoplay.html, pages/licensing.html, pages/privacypolicy.html, pages/termsofservice.html, styles/game.style.css, styles/mainstyle.css
Successfully added loader on all pages. A good, theme matching loader has been added.
Fixes #558 
<hr>
<hr>
--- 
<br>
=> Preloader added

index.html
Fixed the disappearance of the footer copyright section.
Fixes #658 
<hr>
<hr>
https://github.com/user-attachments/assets/d4921f20-92cc-47e2-b803-8b72ca44dbd1
--- 
<br>
=> Corrected footer visibility

index.html, styles/mainstyle.css
enhanced the main page container background
Fixes #656
<hr>
<hr>
--- 
<br>
=> enhanced the main page container background

index.html, js/loader.js, pages/404.html, pages/FAQs.html, pages/about.html, pages/contributors.html, pages/game.html, pages/howtoplay.html, pages/licensing.html, pages/privacypolicy.html, pages/termsofservice.html, styles/mainstyle.css
- Issue closes #657 
This pull request addresses the bug described in Issue #657, where the preloader remains visible and blocks access to the page due to server errors preventing the loading of external script files.
- Added preloader JavaScript code directly into the `<script>` tag of each HTML file to bypass `server` issues that were preventing the external script file from loading.
- Implemented `error handling` in the preloader `script` to check if the `#loader` element exists before attempting to modify its display property, preventing potential errors if the element is not found.
- Added a `console.error` message to log an error if the `#loader` element is not present.
- Ensured that preloader functionality works even if the server encounters issues with loading …
=> Fixed Preloader Visibility Issue and Implemented Error Handling

index.html, js/game.js, js/index.js, pages/game.html, styles/game.style.css, styles/index.style.css
I have removed the input column for rows and columns and I have added Difficulty selection. 
Now players can easily select difficulty levels for them and it will also make game board to render on predefined size. 
Fixes #546 
<hr>
<hr>
--- 
<br>
=> Difficulty Feature Added

pages/licensing.html, pages/privacypolicy.html, pages/termsofservice.html
- issue closes #661 
I have added a  dynamic date functionality to legal pages for weekly update and licensing yearly 
<hr>
<hr>
--- 
<br>
=> Added Dynamic Date Functionality to Leagel Pages for Weekly Update and Licensing Yearly 

styles/index.style.css
Made the home page responsive.
Fixes #677 
<hr>
- Made the home page responsive for mobile-view.
- Now, the home page will look good & responsive in mobile view as well.
<hr>
<hr>
https://github.com/user-attachments/assets/c9f9a60c-aa71-41ab-b160-b665eb8c7237
_Please review & merge my pull-request under GSSoC'24_
--- 
<br>
=> Made the home page responsive

styles/howtoplay.css
Hey @ayush-t02 .
closes issue #686 
******What I did******
- Typography and Colors: Updated the font to Comic Sans MS and adjusted the color scheme to match the vibrant and playful style of termsOfServices.css.
- Container Styling: Unified container styles with similar backgrounds, border radii, and box shadows for a consistent look across the site.
- Layout and Spacing: Adjusted margins, paddings, and responsive design elements to ensure a cohesive layout that matches the termsOfServices.css styling.
- Interactive Elements: Updated hover effects, text decorations, and button styles to be consistent with the design patterns found in termsOfServices.css.
<hr>
<hr>
https://github.com/user-attachments/assets/87ccd85a-a7d3-471c-9508-07fae2024ab9
**Please take a look and review it**
=> styled the "how to play" to align it with the design style of "termsOfServices"

index.html
Hello Project Admin
I Added Icons to Navbar - Solved #693 
Kindly go through this PR @ayush-t02
=> Added Icons to Navbar

js/game.js, styles/game.style.css
issue closes #696 
Earlier, the avatars for players were not displaying after starting the game. Instead, only the alt text was visible.
Additionally, when attempting to change avatars, none of the 20 available images were displaying, showing only their alt text.
**I have resolved the issue, please take a look -** 
Now the avatars are displaying.
**BEFORE :** 
https://github.com/user-attachments/assets/f7b8df60-d985-4390-aa22-1917f74c6a9f
**AFTER :** 
https://github.com/user-attachments/assets/dbb8dc34-0941-470c-9843-e4ff94d49e5a
<hr>
--- 
<br>
=> ✔️Fixed Avatars Not Displaying During Avatar Selection

js/game.js, pages/FAQs.html, pages/game.html, styles/FAQs.css, styles/game.style.css
1.Enhance the UI of Initial game.html
2.Fixed the broken link to index.html
3. Fixed the avator broken img src path
4.Fixed the Faq Page UI
5.Fixed the FAQ page footer 
6.Removed Scrollbars in FAQ page
Fixes #695 
<hr>
- [ x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x] I have performed a self-review of my own code or work.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [x ] …
=> Fixed the Navigation in game.html and Fixed FAQ page

js/contributors.js, pages/contributors.html, styles/contributors.css
Fixes #689 
- _Added Pagination Feature in Contributors page_
- _Now, user can view all the contributors of this project._
<hr>
<hr>
https://github.com/user-attachments/assets/4412bc1f-9545-498a-b6cc-8fab3aae1691
--- 
<br>
=> Added Pagination Feature in Contributors page

README.md, pages/howtoplay.html
hey @ayush-t02 
issue closes #697 
i have fixed the tutorial issue in readme and howtoplay 
#715 
<hr>
<hr>
--- 
<br>
=> Fixed tutorial issue in Readme and HowToBelow

pages/howtoplay.html, pages/licensing.html, pages/privacypolicy.html, pages/termsofservice.html
issue close #687 
I have added the favicons to all the pages in the footer 
as you can see - 
<hr>
--- 
<br>
=> ✔️Added Favicons to All the pages!

styles/index.style.css
Fixed the feedback form for 480px
Fixes #683
<hr>
<hr>
--- 
<br>
=> Fixed the feedback form for 480px

pages/FAQs.html, pages/about.html, pages/contributors.html, pages/howtoplay.html
hey @ayush-t02 
issue closes #716 
I have added the icons to all the links present in the home page's Navbar and Footer to All the Non-Home pages Which were earlier not present there.
As you can see -
https://github.com/user-attachments/assets/574021c2-a741-48fb-8f30-a02147d988c7
Please take a look and review it.
<hr>
<hr>
--- 
<br>
=> ✔️Added Icons to All Non-Home Pages !

pages/FAQs.html, pages/about.html, pages/contributors.html, pages/howtoplay.html
Fixes #733 
- Fixed the paths of navbar links of all pages.
- Now, all the links of navbar will redirect to correct path.
<hr>
<hr>
https://github.com/user-attachments/assets/5c49255b-ee12-4a27-a256-edf5fdb5388f
@ayush-t02 please review & merge my pull-request under GSSoC'24.
--- 
<br>
=> Fixed the paths of navbar links of all pages

index.html, js/validation.js, pages/game.html, styles/index.style.css
Fixed validation to get player count and process validation.
Improved disable button styling
disabled button functionality added
Fixes #719  
<hr>
<hr>
--- 
<br>
=> Validation fixed for player count

styles/global.css
- Made the Licensing page responsive.
- Now, the page will be responsive in all the views.
Fixes #743 
<hr>
<hr>
https://github.com/user-attachments/assets/0c6c6499-1118-4290-8fc2-aa71bacfabb7
--- 
<br>
@ayush-t02 please review & merge my pull-request under GSSoC'24
=> fix: Made the Licensing page responsive

pages/FAQs.html, pages/about.html, pages/contributors.html, pages/howtoplay.html, pages/testimonials.html, styles/navbar.css
Added testimonials navigation link to the following pages:
- how-to-play page
- about page
- FAQ page
- contributors page
- testimonials page
Fixes #754
<hr>
<hr>
--- 
<br>
=> Added testimonials

js/FAQs.js
I made the FAQs to collapse automatically when another FAQs is expanded.
Fixes #756
<hr>
<hr>
https://github.com/user-attachments/assets/26ce7771-80aa-4436-a948-07daeb8ca9f3
--- 
<br>
=> Made FAQs auto collapse

pages/about.html
Corrected the placement of the main section in About Page, which was earlier blocking the clicking of the repo-button
Fixes #755 
<hr>
<hr>
--- 
<br>
=> Corrected the page

js/nav.footer.js, styles/mainstyle.css
Made the discord and github icon color when hovered
Fixes #765
<hr>
<hr>
https://github.com/user-attachments/assets/f6eb3caa-8cd3-4304-93a3-7719a7283a05
--- 
<br>
=> Colored the icons

index.html, js/nav.footer.js
The relative location of the home page is different than the other pages, so when the same nav-bar was being used for all pages, the address was coming out to be wrong in the case of the home-page
Fixes #769 
<hr>
<hr>
--- 
<br>
=> Corrected Address
